apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demoapi-ingress
  namespace: demo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: demo.local        # domain tự định nghĩa
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demoapi
            port:
              number: 80
